# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set env
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        echo "CURRENT_BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

    - name: Print env
      run: |
        echo $GITHUB_REF
        echo $RELEASE_VERSION
        echo $CURRENT_BRANCH
        echo $GITHUB_ENV
        echo ${{ env.RELEASE_VERSION }}
        echo ${{ github.ref }}
        echo ${{ github.head_ref }}
        echo ${{ github }}


    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn clean package
      
    - name: Debug
      run: ls -l
      
    - uses: docker/setup-buildx-action@v1

    - name: Edit image tag
      run: sed -i 's/<TAG>/${{ env.RELEASE_VERSION }}/' Dockerrun.aws.json
      
    - name: Docker Login
      uses: docker/login-action@v1.6.0
      with:
        # Username used to log against the Docker registry
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.1.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: captainspof/click-count:${{ env.RELEASE_VERSION }}
        
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

    - name: Generate deployment package
      run: zip -r deploy.zip Dockerrun.aws.json

    - name: Deploy to EB staging
      if: github.event.release.prerelease && github.ref == 'refs/heads/feature/gh-actions'
      uses: einaregilsson/beanstalk-deploy@v14
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: ${{ secrets.BEANSTALK_STAGING_APPLICATION_NAME }}
        environment_name: ${{ secrets.BEANSTALK_STAGING_ENVIRONMENT_NAME }}
        version_label: ${{ env.RELEASE_VERSION }}
        region: ${{ secrets.AWS_REGION }}
        deployment_package: deploy.zip
        use_existing_version_if_available: true

    - name: Deploy to EB production
      if: (!github.event.release.prerelease) && github.ref == 'refs/heads/master'
      uses: einaregilsson/beanstalk-deploy@v14
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: ${{ secrets.BEANSTALK_PRODUCTION_APPLICATION_NAME }}
        environment_name: ${{ secrets.BEANSTALK_PRODUCTION_ENVIRONMENT_NAME }}
        version_label: ${{ env.RELEASE_VERSION }}
        region: ${{ secrets.AWS_REGION }}
        deployment_package: deploy.zip
        use_existing_version_if_available: true
